import org.apache.tools.ant.taskdefs.condition.Os

apply plugin: 'com.android.application'

buildDir = "../build"
def getDistManidfestXML(output)
{
    return new File(output.getProcessManifestProvider().get().multiApkManifestOutputDirectory.get().getAsFile(), "AndroidManifest.xml")
}

project.afterEvaluate {
    println '最后执行'
    android.applicationVariants.all { variant ->
        String variantName = variant.name.capitalize()  //3.3
        variant.outputs.each { output ->
            output.processManifest.doLast {
//                println "输出"
                def manifestOutFile = getDistManidfestXML(output)
                def manifestContent =  manifestOutFile.getText('UTF-8')
                def readPhone = "<uses-permission android:name=\"android.permission.READ_PHONE_STATE\" />"
                def readPhoneReplace = "<!-- <uses-permission android:name=\"android.permission.READ_PHONE_STATE\" /> -->"
                def callPhone = "<uses-permission android:name=\"android.permission.CALL_PHONE\" />"
                def callPhoneReplace = "<!-- <uses-permission android:name=\"android.permission.CALL_PHONE\" /> -->"
                manifestContent = manifestContent.replace(readPhone,readPhoneReplace)
                manifestContent = manifestContent.replace(callPhone,callPhoneReplace)
//                println "执行字符串操作" + manifestContent
                manifestOutFile.write(manifestContent)
            }
        }
    }
}
android {
    compileSdkVersion PROP_COMPILE_SDK_VERSION.toInteger()
    buildToolsVersion PROP_BUILD_TOOLS_VERSION
    ndkPath PROP_NDK_PATH

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        //applicationId "com.casino.brl"
        minSdkVersion PROP_MIN_SDK_VERSION
        targetSdkVersion PROP_TARGET_SDK_VERSION
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            ndk { abiFilters PROP_APP_ABI.split(':') }
        }
    }

    sourceSets.main {
        java.srcDirs "java", "src"
        res.srcDirs 'res'
        jniLibs.srcDirs 'libs'
        manifest.srcFile "AndroidManifest.xml"
        assets.srcDir "../assets"
        jniLibs {
            // Vulkan validation layer
            // srcDir "${android.ndkDirectory}/sources/third_party/vulkan/src/build-android/jniLibs"
        }
    }

    signingConfigs {

        release {
            storeFile file("../keystore/keystores/com.casino.brl10001.keystore")
            storePassword RELEASE_STORE_PASSWORD
            keyAlias "com.casino.brl10001"
            keyPassword RELEASE_KEY_PASSWORD
        }
    }

    buildTypes {
        release {
            debuggable true
            jniDebuggable true
            renderscriptDebuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                signingConfig signingConfigs.release
            }
            ndk { abiFilters PROP_APP_ABI.split(':') }
            //resValue  "string", "app_name", "${PROP_APP_NAME}"
        }

        debug {
            debuggable true
            jniDebuggable true
            renderscriptDebuggable true
            ndk { abiFilters PROP_APP_ABI.split(':') }
            // resValue  "string", "app_name", "${PROP_APP_NAME}-dbg"
            // applicationIdSuffix ".debug"
        }
    }

    repositories {
        mavenCentral()
    }
}



dependencies {
    implementation fileTree(dir: '../libs', include: ['*.jar','*.aar'])
    implementation fileTree(dir: 'libs', include: ['*.jar','*.aar'])
    implementation project(':libservice')
    implementation project(':libcocos')


    implementation 'com.adjust.sdk:adjust-android:4.28.9'
    implementation 'com.android.installreferrer:installreferrer:2.2'
    implementation 'com.adjust.sdk:adjust-android-webbridge:4.28.9'
    implementation 'com.google.android.gms:play-services-ads-identifier:17.0.1'
    implementation 'com.appsflyer:af-android-sdk:6.13.1'
}

