import { _decorator } from "cc";
import { AccountInfo } from "../module/userinfo/accountInfo";
import { BankCards } from "../module/userinfo/bankCards";

const { ccclass, property } = _decorator;

@ccclass('CommonName')
export default class CommonName {
    static readonly Currency = {
        Symbol: "R$",
        Name: "BRL",
    }

    //事件名称
    static readonly EVENT = {
        Respon_Refresh_UserInfo: "respon-refresh-userinfo",
        Respon_Marqueen_Ntf: "respon-marqueen-ntf",
        Respon_GameServer_Addr: "respon-gameserver-addr",
        Respon_GameServer_Url: "respon-gameserver-url",
        Respon_GameListNtf: "respon-gamelist-ntf",
        RedPoint_Event: "redpoint_event",
        Respon_Facebook_login: "respon_facebook_login",
        Respon_Line_login: "respon_line_login",
        Respon_Facebook_Share: "respon_facebook_share",
        Respon_VerifyCode: "respon_verify_code",
        Game_Version_Update: "Game_Version_Update",
        HotUpdate_Success: "HotUpdate_Success",
        Back_To_Home: "Back_To_Home",
        Show_Like: "Show_Like",
        ResponSaveToPhoto: "ResponSaveToPhoto",
        LimitRegister: "LimitRegister",
        ResponBindGuest: "ResponBindGuest",
        ResponResetPwd: "ResponResetPwd",
        FirstRechargeLimitTime: "FirstRechargeLimitTime",
        FirstRechargeRedPoint: "FirstRechargeRedPoint",
        WeeklyCardReward: "WeeklyCardReward",
        RechargePartyReward: "RechargePartyReward",
        BetReturns: "BetReturns",
        Game_Update_Progress:"Game_Update_Progress",
        Game_Update_Failed:"Game_Update_Failed",
        Game_Update_Success:"Game_Update_Success",
        FirstChargeNewStatus: "FirstChargeNewStatus",
        Update_USER_COIN:"Update_USER_COIN",
        GoToHall: "GoToHall",
        GoToVIP: "GoToVIP",
        CloseRecharge:"CloseRecharge",
        RankHistory:"RankHistory",
        UpdateActivityPopUp:"UpdateActivityPopUp",
        UpdateEmailRedDot: "UpdateEmailRedDot",
        UpdateRewardRedDot: "UpdateRewardRedDot",
        UpdateRegressionMain: "UpdateRegressionMain",
        UpdateRegressionRedDot: "UpdateRegressionRedDot",
    }

    //模块名称
    static readonly MODULE = {
        Hall: "Hall",
        ActivityList: "ActivityList",
        BankBind: "BankBind",
        CustomerService: "CustomerService",
        Dialog: "Dialog",
        Email: "Email",
        Loading: "Loading",
        Login: "Login",
        NetPrompt: "NetPrompt",
        Promotion: "Promotion",
        Recharge: "Recharge",
        SafeBox: "Safebox",
        Toast: "Toast",
        UserInfo: "UserInfo",
        Vip: "Vip",
        WebviewPage: "WebviewPage",
        Withdraw: "WithDraw",
        Reward: "Reward",
        BoardInfo: "BoardInfo",
        Setting: "Setting",
        ShareQRCode: "ShareQRCode",
        SuperMarqueen: "SuperMarqueen",
        MoneyNotEnough: "MoneyNotEnough",
        Guide: "GuideModule",
        GuideAward: "GuideAward",
        GroupReward: "GroupReward",
        Register: "Register",
        RegisterReward: "RegisterReward",
        FirstRecharge: "FirstRecharge",
        FirstRechargeDesc: "FirstRechargeDesc",
        ScreenShot: "ScreenShot",
        LoginReward: "LoginReward",
        CoinFly: "CoinFly",
        WeeklyCard: "WeeklyCard",
        RechargeParty: "RechargeParty",
        HelpDesc: "HelpDesc",
        BetReturns: "BetReturns",
        RechargeNew: "RechargeNew",
        RechargeRecordNew: "RechargeRecordNew",
        ChargeGift: "ChargeGift",
        ChargeDialog: "ChargeDialog",
        TurnTable:"TurnTable",
        EarnMoney:"EarnMoney",
        EarnMoneyNew:"EarnMoneyNew",
        WithdrawNew:"WithdrawNew",
        GameListNew:"GameListNew",
        RechargeRecord:"RechargeRecord",
        WithdrawNewRecord:"WithdrawNewRecord",
		MemberDetails:"MemberDetails",
		BalanceRecord:"BalanceRecord",
        BalanceReport:"BalanceReport",
        BalanceReportDetails:"BalanceReportDetails",    
        AccountInfo:"AccountInfo",  
        BankCards:"BankCards",  
        ActivityRank:"ActivityRank",  
        ActivityRankHistory:"ActivityRankHistory", 
        ActivityRankPopUp:"ActivityRankPopUp",
        ActivityRankRule:"ActivityRankRule",
        ActivityBackFlow:"ActivityBackFlow",
        Wallet:"Wallet",
        ActivityFirstCharge: "ActivityFirstCharge",
        HeadInfo: "HeadInfo",
        ActivityDailyBonus:"ActivityDailyBonus",
        ForgotPassword: "ForgotPassword",
        Reminder: "Reminder",
        MonthlyCard:"MonthlyCard",
        EmailDetails:"EmailDetails",
        CustomerSupport: "CustomerSupport",
        ActivityRegression:"ActivityRegression",
        ActivityRegressionGiftPack: "ActivityRegressionGiftPack",
        ActivityTreasureBowl:"ActivityTreasureBowl",
        RewardsToday: "RewardsToday",
        CumulativeRrecharge:"CumulativeRrecharge",
        ConsecutiveRrecharge:"ConsecutiveRrecharge",
        ReturningSignin:"ReturningSignin",
        ReturningTurntable:"ReturningTurntable",
        RewardCode: "RewardCode",
        EarnMoneyShare:"EarnMoneyShare",
        RechargeWheel:"RechargeWheel",
        RechargewheelRewards:"RechargewheelRewards",
        ChannelEntrance: "ChannelEntrance",
        GiftCode: "GiftCode",
        GiftCodeResult: "GiftCodeResult",
        DateSelect: "DateSelect",
        EarnMoneyDetail: "EarnMoneyDetail",
        EarnMoneySubordinateData: "EarnMoneySubordinateData",
        EarnMoneyRules:"EarnMoneyRules",
        ActivitySocialMedia:"ActivitySocialMedia",
        ActivityShareTurntable: "ActivityShareTurntable"
    }

    //当前可展示module
    static readonly INVALID_MODULE = {
        // "Hall": "Hall",
        // "ActivityList": "ActivityList",
        // "BankBind": "BankBind",
        // "CustomerService": "CustomerService",
        // "Dialog": "Dialog",
        // "Email": "Email",
        // "Loading": "Loading",
        // "Login": "Login",
        // "NetPrompt": "NetPrompt",
        // "Safebox": "Safebox",
        // "Toast": "Toast",
        // "UserInfo": "UserInfo",
        // "Vip": "Vip",
        // "WebviewPage": "WebviewPage",
        // "WithDraw": "WithDraw",
        // "Reward": "Reward",
        // "BoardInfo": "BoardInfo",
        // "Setting": "Setting",
        // "ShareQRCode": "ShareQRCode",
        // "SuperMarqueen": "SuperMarqueen",
        // "MoneyNotEnough": "MoneyNotEnough",
        // "GuideModule": "GuideModule",
        // "GuideAward": "GuideAward",
        // "Register": "Register",
        // "RegisterReward": "RegisterReward",
        // "FirstRecharge": "FirstRecharge",
        // "FirstRechargeDesc": "FirstRechargeDesc",
        // "ScreenShot": "ScreenShot",
        // "LoginReward": "LoginReward",
        // "CoinFly": "CoinFly",
        // "WeeklyCard": "WeeklyCard",
        // "RechargeParty": "RechargeParty",
        // "HelpDesc": "HelpDesc",
        // "BetReturns": "BetReturns",
    }


    static readonly PUBLIC_SOUNDURL = {
        Bgm: "sound/bgm/homebg",
        ButtonClick: "sound/public/ButtonClick",
        GameClick: "sound/public/GameClick",
        GameTypeClick: "sound/public/GameTypeClick",
        WindowClose: "sound/public/WindowClose",
        WindowOpen: "sound/public/WindowOpen",
        Reward: "sound/public/Congratulation"
    }

    static readonly ITEM_CONFIG = {
        "1": { name: "email_gold", type: 1, spriteIndex: 0, desc: "email_gold_desc" }
    }

    static readonly LANGUAGE = {
        ZH: "zh",
        EN: "en",       
        PT: "pt",
    }

    static ErrorCode = {
        AccountBalanceNotEnough: 8,
        KickWithoutMoney: 9997,
        NetError: 9998,
        MoneyNotEnough: 9999,
        UnknownError: 10000,
    }
}
